# Generated by Django 4.2.1 on 2023-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizz_title', models.CharField(default='', max_length=200, verbose_name='Quizz Title')),
                ('quizz_category', models.CharField(default='', max_length=200, verbose_name='Quizz Category')),
            ],
            options={
                'verbose_name': 'Quizz Object',
                'verbose_name_plural': 'Quizz Objects',
            },
        ),
    ]
