# Generated by Django 4.2.1 on 2023-12-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question', models.CharField(default='', max_length=1000, verbose_name='Quiz question')),
                ('choice_1', models.CharField(default='', max_length=1000, verbose_name='Choice one')),
                ('choice_2', models.CharField(default='', max_length=1000, verbose_name='Choice two')),
                ('choice_3', models.CharField(default='', max_length=1000, verbose_name='Choice three')),
                ('choice_4', models.CharField(default='', max_length=1000, verbose_name='Choice four')),
                ('response', models.CharField(default='', max_length=1000, verbose_name='Response')),
            ],
            options={
                'verbose_name': 'Quiz data',
                'verbose_name_plural': 'Quiz datas',
            },
        ),
        migrations.CreateModel(
            name='QuizObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(default='', max_length=200, unique=True, verbose_name='Quiz Title')),
                ('quiz_category', models.CharField(default='', max_length=200, verbose_name='Quiz Category')),
            ],
            options={
                'verbose_name': 'Quiz Object',
                'verbose_name_plural': 'Quiz Objects',
            },
        ),
        migrations.DeleteModel(
            name='QuizzObject',
        ),
        migrations.AddField(
            model_name='quizdata',
            name='quiz_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_sample.quizobject', verbose_name='Quiz about'),
        ),
    ]
